### ISSUE TITLE
require is not defined when bundling code with node

### ISSUE THREAD

**Issue by Prince-Hamza** [mzusin/toolcool-range-slider#4] opened 2022-12-13 15:11 UTC
it works fine with when used with react only. when i build with yarn build for nodejs server (because i have apis) . server shows a blank page .console says require is not defined.

**Comment by toolcool-org** [comment] 2022-12-13 23:59
The slider can't work in node.js only as it requires DOM. What is your use case?

**Comment by toolcool-org** [comment] 2022-12-30 07:39
Closing because there was no further response.

**Comment by awais-amjed** [comment] 2023-05-19 12:43
Getting this Error in Production.

I am using ReactJS v18
Slider works fine in dev mode but when I build for production and deploy it on Firebase I get this error.

`Uncaught ReferenceError: require is not defined`

I have tried to isolate the issue to this import

`import 'toolcool-range-slider';`

Removing this import, the code works fine in production but obviously the Slider is not displayed :D

**Comment by awais-amjed** [comment] 2023-05-19 12:50
I am using create-react-app

**Comment by mzusin** [comment] 2023-05-19 12:51
How to you import the slider to your component? Please share some code sample.

**Comment by awais-amjed** [comment] 2023-05-19 12:55
Following the guide here exactly: https://toolcool-range-slider.mzsoft.org/pages/react-typescript.html

Here is my code related to the slider:


```
import 'toolcool-range-slider/dist/plugins/tcrs-marks.min.js';
import 'toolcool-range-slider';

<tc-range-slider
      id={`slider-${id}`}
      data={data}
      value={value}
      ref={ sliderRef }
      slider-bg={color1}
      slider-bg-hover={color1}
      slider-bg-fill={color1}
      slider-height="2px"
      slider-width={min768 ? "380px" : null}
      slider-radius="2px"
      pointer-width="18px"
      pointer-height="18px"
      pointer-bg="white"
      pointer-bg-hover="white"
      pointer-bg-focus="white"
      pointer-border="0 solid transparent"
      pointer-border-hover="0 solid transparent"
      pointer-border-focus="0 solid transparent"
      pointer-shadow="2px 7px 8px 0 rgba(0, 0, 0, 0.15)"
      pointer-shadow-hover="2px 7px 8px 0 rgba(0, 0, 0, 0.15)"
      pointer-shadow-focus="2px 7px 8px 0 rgba(0, 0, 0, 0.15)"
      mousewheel-disabled="true"

      marks="true"
      min={minShown}
      max={maxShown}
      step={step}
      marks-count={0}
      marks-values-count={marksValueCount ?? (((maxShown - minShown) / step) + 1)}
      marks-color="transparent"
      marks-values-color="#A6A6A6"
    />
```

**Comment by awais-amjed** [comment] 2023-05-19 12:56
Produces Sliders like this in dev mode:

![image](https://github.com/mzusin/toolcool-range-slider/assets/73714615/d74b35fb-6426-4fcc-b5b5-c4d5f2e7c8b5)

**Comment by mzusin** [comment] 2023-05-19 12:57
OK, I'll try to create a react app with the slider and reproduce this error.

**Comment by awais-amjed** [comment] 2023-05-19 12:57
ok Thanks

**Comment by awais-amjed** [comment] 2023-05-19 13:21
So I removed the package from package.json and imported it using the script from cdn in my index.html file like this

![image](https://github.com/mzusin/toolcool-range-slider/assets/73714615/9873061b-5b69-4256-9874-8d5991995377)

This works in Production.

So I think the issue is in the bundling process somewhere.

**Comment by mzusin** [comment] 2023-05-19 13:46
Yes, you're right, It looks like some conflict with babel package in create react app. I'm still investigating.

**Comment by mzusin** [comment] 2023-05-26 08:55
It's hard to believe, but it seems that create react app is no longer being maintained and kind of deprecated. They all recommend Vite as a replacement.
- https://github.com/facebook/create-react-app/issues/13140
- https://github.com/facebook/create-react-app/issues/12974

Here is a little more information
https://github.com/reactjs/react.dev/pull/5487#issuecomment-1409720741

Apparently, it is unlikely that someone will soon answer the ticket I opened.

**Closed** 2023-06-06 03:04 UTC
Labels: no-issue-activity
